[workspace]
channels = ["conda-forge", "bioconda", "bioconda", "conda-forge"]
name = "bioinfor-wf-bashscipt-qc-ngs"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
fastqc = ">=0.12.1,<0.13"
multiqc = ">=1.32,<2"
